# Coding Temple's Data Analytics Program  
---
# Advanced Python - Intro to `numpy`
---



## Part 1: Working with `numpy`


### 1.1 Importing `numpy`

We've already used the `numpy` package by importing it and assigning it the standard alias of `np`. Do this again in the following cell - the more you practice typing these lines of code, the easier it will be to remember.

In [3]:
# Import numpy and assign it the standard alias
# YOUR CODE HERE
import numpy as np

### 1.1 Solution - Run this cell to check your answer in 1.1. Please do not edit the values in this cell!

In [4]:
# DO NOT EDIT THIS CELL
assert np.__name__ == 'numpy', 'Make sure that you have properly imported numpy and aliased it as np!'

### 1.2 Generate random numbers

Create a `(5,3)` `numpy` array of random integer values between 0 and 100.

Use the the `random()` method in numpy to generate these integers. Name your new variable `myarray`. You should also print the array to check it's dimensions and values.

In [6]:
# Generate your random numbers
np.random.seed(1) #Seed generated for reproducibility

#YOUR CODE HERE
myarray = np.random.randint(0,101,(5,3))

# Print out the array
myarray

array([[37, 12, 72],
       [ 9, 75,  5],
       [79, 64, 16],
       [ 1, 76, 71],
       [ 6, 25, 50]])

### 1.2 Solution - Run the following cell to check your answer.

In [7]:
#DO NOT EDIT THIS CELL

#Verify the array was created with the correct name and has the proper shape
assert myarray.shape == (5,3), 'Make sure you create an array with the proper shape!'

### 1.3 Calculate BMI 

Using the two lists provided, please calculate the BMI(body mass index) of each individual using NDArrays. Save the variable containing your results as `bmi`

The formula for BMI in pounds and inches can be defined as: $BMI= \frac{703 * weight} {(height)^2}$

In [11]:
height = [55, 120, 90, 100]
weight = [170, 180, 190, 200]
height = np.array(height)
weight = np.array(weight)
bmi = weight/(height**2) *703
bmi = np.round(bmi, 2)
print(bmi)

[39.51  8.79 16.49 14.06]


### 1.3 Solution: Run the following cell to check your answer.

In [12]:
assert 'bmi' in dir() , 'Make sure you have saved your results to the proper variable name!'
assert type(bmi) == np.ndarray, 'Make sure that you made the calculation using an NDArray for both height and weight!'

### 1.4 Create a function 

Create a function named `my_func` that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [22]:
def my_func():
    rows = int(input('how many rows would you like? '))
    columns = int(input('how many columns would you like? '))
    dtype = input('please type int or float for the data type you want  ')
    matrix = np.random.randint(0,101, size=(rows,columns)).astype(dtype)
    return matrix

print(my_func())

[[65. 77.]
 [ 3.  0.]]


### 1.5 Array practice

Time for some more practice. Run each of these tasks in the separate code cell listed below:

1.  Return the first row
2.  Return the last column
3.  Return the third column values from the 4th and 5th rows
4.  Multiply every value in the array by 2
5.  Divide every value by 3
6.  Increase the values in the first row by 12
7. Calculate the mean of the first column
8. Calculate the median of the array _after_ removing the 2 smallest values in the array
9. Calculate the standard deviation of the first 3 rows
10. Return values greater than 25 in the second column
11. Return values less than 40 in the array

In [42]:
# 1. Return the first row:
np.random.seed(9)
arr1 = np.random.randint(25, size=(5,5))
print(f'this is the array im using for this example: \n{arr1}')
print(f'first row of the array: {arr1[0]}')

this is the array im using for this example: 
[[21 22 24 22  1]
 [22 20  8 17 24]
 [21  1  0 14 24]
 [10 24 10 24 12]
 [18 22 24  1 24]]
first row of the array: [21 22 24 22  1]


In [44]:
# 2. Return the last column
print(f'this is the last column of my array: \n {arr1[:,-1]}')

this is the last column of my array: 
 [ 1 24 24 12 24]


In [46]:
# 3. Return the third column values from the 4th and 5th rows
print(f'this is the third column value from the 4th row: {arr1[3][2]}')
print(f'this is the third column value from the 5th row: {arr1[4][2]}')


this is the third column value from the 4th row: 10
this is the third column value from the 5th row: 24


In [47]:
# 4. Multiply every value in the array by 2
print(f'here is my array doubled: \n {arr1*2}')

here is my array doubled: 
 [[42 44 48 44  2]
 [44 40 16 34 48]
 [42  2  0 28 48]
 [20 48 20 48 24]
 [36 44 48  2 48]]


In [48]:
# 5. Divide every value by 3
print(f'here is my array divided by 3: \n{arr1/3}')


here is my array divided by 3: 
[[7.         7.33333333 8.         7.33333333 0.33333333]
 [7.33333333 6.66666667 2.66666667 5.66666667 8.        ]
 [7.         0.33333333 0.         4.66666667 8.        ]
 [3.33333333 8.         3.33333333 8.         4.        ]
 [6.         7.33333333 8.         0.33333333 8.        ]]


In [49]:
# 6. Increase the values in the first row by 12
print(f'my first row increased by 12 {arr1[0]+12}')

my first row increased by 12 [33 34 36 34 13]


In [50]:
# 7. Calculate the mean of the first column
print(f'the avaerage of the first column: {np.mean(arr1[:,0])}')

the avaerage of the first column: 18.4


In [51]:
# 8. Calculate the median of the array after removing the 2 smallest values in the array
arr1 = np.sort(arr1)
arr1 = arr1[2:]
print(f'this is the median after taking the 2 smallest values: {np.median(arr1)}')

this is the median after taking the 2 smallest values: 18.0


In [57]:
# 9. Calculate the standard deviation of the first 3 rows
# Generate a new array to work on
np.random.seed(2) # New seed for new array
arr2 = np.random.randint(100, size=(5,3))
print(f'the standard deviation for new array: {np.std(arr1[0:3,:])}')


the standard deviation for new array: 8.850360946813915


In [60]:
# 10. Return values in the second column greater than 25
G25 = arr2[:,1] > 25
print(f'the values in the second column that are greater than 25 are: {arr2[G25]}')


the values in the second column that are greater than 25 are: [[22 43 82]
 [49 95 75]
 [85 47 63]]


In [59]:
# 11. Return values < 40 in the array
l40 = arr2 < 40
print(f'all values under 40: {arr2[l40]}')

all values under 40: [15 22  7 34]


### Solution 1.5: Run the following cell to view the solution for each of the above tasks.

A new array will be generated to demonstrate the solution - the values will not be the same as your array. But the code for each task will still apply.

In [ ]:
# DO NOT EDIT THIS CELL
# SOLUTION 1.3

# SOLUTION: Make sure you have completed all of the above tasks
# Generate your random numbers (NEW ARRAY)
myarray = np.random.randint(100, size=(5, 3))
print('The generated array: \n', myarray)
print('\n')

# 1. Return the first row:
print('1. The first row: ', myarray[0])
print('\n')

# 2. Return the last column
print('2. The last column: ', myarray[:,-1])
print('\n')

# 3. Return the third column values from the 4th and 5th rows
print('3. The 3rd column, 4th & 5th rows: ', myarray[3:5,2])
print('\n')

# 4. Multiply every value in the array by 2
# (operates on the original array)
print('4. Multiply by 2: \n', myarray * 2)
print('\n')

# 5. Divide every value by 3
# (operates on the original array)
print('5. Divide by 3: \n', myarray / 3)
print('\n')

# 6. Increase the values in the first row by 12
# (operates on the original array)
print('6. Add 12 to the first row: \n', myarray[0,:] + 12)
print('\n')

# 7. Calculate the mean of the first column
print('7. The mean of the 1st column: ', myarray[:,0].mean())
print('\n')

# 8. Calculate the median of the array after removing the 2 smallest values in the array
# flatten and sort (axis=None does the flattening)
myarray = np.sort(myarray, axis=None)
# remove two smallest values
myarray = myarray[2:]
# calculate the median
print('8. The median after removing the 2 smallest values: ', np.median(myarray))
print('\n')

# 9. Calculate the standard deviation of the first 3 rows
# Generate new array first:
myarray = np.random.randint(100, size=(5, 3))
# Then calculate the std:
print('9. The standard deviation is: ', np.std(myarray[0:3,:]))
print('\n')

# 10. Return values in the second column greater than 25
# create a Boolean mask where values in the 2nd column > 25 are True
condition = myarray[:,1] > 25
# Apply the mask
print('10. All values in 2nd column > 25: \n', myarray[condition])
print('\n')

# 11. Return values < 40 in the array
# create another Boolean mask for values < 40
condition = myarray < 40
# apply the mask
print('11. All values < 40: \n', myarray[condition])